'use client'
import Link from 'next/link'; import {usePathname,useRouter} from 'next/navigation'; import {useEffect,useState} from 'react'; import {api,errorText,fmtDate,fmtId,fmtLift,fmtMoney,fmtNum,LoopRun,SystemStatus,EvidenceRecord} from '@/lib/api';
const tabs=[['/','Overview','blue'],['/red-team','Red Team','violet'],['/sandbox','Sandbox','orange'],['/blue-team','Blue Team','green'],['/labs','Labs','orange'],['/evaluation','Evaluation','blue']];
export function useStatus(){const [status,setStatus]=useState<SystemStatus|null>(null);const [error,setError]=useState('');useEffect(()=>{let timer:ReturnType<typeof setTimeout>;let alive=true;const load=async()=>{try{const s=await api.status();if(alive)setStatus(s);timer=setTimeout(load,s.running_loop?4000:30000)}catch(e){if(alive)setError(errorText(e));timer=setTimeout(load,30000)}};load();return()=>{alive=false;clearTimeout(timer)}},[]);return {status,error}}
export function TopBar(){const path=usePathname();const {status,error}=useStatus();const running=!!status?.running_loop;const state=running?'LOOP RUNNING':status?.scheduler?.enabled?'SCHEDULED':'IDLE';return <header className="topbar"><div className="brand"><span className="brandmark">PD</span><div><strong>Payment Defense Twin</strong><small>Continuous Red/Blue Loop</small></div></div><nav>{tabs.map(([href,label,color])=><Link className={`${path===href?'active ':''}${color}`} href={href} key={href}>{label}</Link>)}</nav><div className={`status ${running?'running':state==='SCHEDULED'?'scheduled':''}`} title={status?.scheduler?.next_run_at?`Next run ${fmtDate(status.scheduler.next_run_at)}`:error||undefined}><i/> {state}</div></header>}
export function Shell({children}:{children:React.ReactNode}){return <><TopBar/><main className="main">{children}</main></>}
export function PageHead({eyebrow,title,subtitle}:{eyebrow:string;title:string;subtitle:string}){return <div className="pagehead"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div></div>}
export function Panel({title,children,action}:{title:string;children:React.ReactNode;action?:React.ReactNode}){return <section className="panel"><div className="panelhead"><h2>{title}</h2>{action}</div>{children}</section>}
export function Empty({children='No data yet'}:{children?:React.ReactNode}){return <div className="empty">{children}</div>}
export function Badge({children,tone='muted'}:{children:React.ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
export function Kpis({status}:{status:SystemStatus|null}){const b=status?.buffer,k=status?.kb,m=status?.model,r=status?.latest_run;const data=[['KB FAMILIES',k?.total_families],['SIMULATABLE',k?.simulatable_families],['BUFFER PAYMENTS',b?.payment_records],['BLOCK / BYPASS',b?`${b.blocked??'—'} blocked · ${b.bypassed??'—'} bypassed`:null],['ACTIVE MODEL',m?.version||'none'],['LATEST LOOP',r?.status||null]];return <div className="kpis">{data.map(([label,value],i)=><div className="kpi" key={label as string}><span>{label}</span><strong>{value??'—'}</strong><small>{i===1?'direct + proxy':i===4?m?.model_type||'No model loaded':i===5&&r?`${fmtId(r.id)}${r.score_lift!=null?` · ${fmtLift(r.score_lift)} lift`:''}`:''}</small></div>)}</div>}
export function RunTable({runs}:{runs:LoopRun[]}){return <div className="tablewrap"><table><thead><tr><th>Started</th><th>Status</th><th>Trigger</th><th>Families</th><th>Buffer</th><th>Score Lift</th><th>Verify</th></tr></thead><tbody>{runs.map(r=><tr key={r.id}><td className="mono">{fmtDate(r.started_at)}</td><td><Badge tone={r.status}>{r.status}</Badge></td><td>{r.trigger||'—'}</td><td>{r.families_count??'—'}</td><td>{r.buffer_payments??'—'} / {r.buffer_bypassed??'—'}</td><td className="mono">{fmtLift(r.score_lift)}</td><td>{r.verify_decision||'—'}</td></tr>)}</tbody></table>{!runs.length&&<Empty>Awaiting completed loop run</Empty>}</div>}
export function EvidenceTable({records,compact=false}:{records:EvidenceRecord[];compact?:boolean}){return <div className="tablewrap"><table><thead><tr><th>Time</th><th>Family</th><th>Step</th><th>Decision</th><th>Evasion</th><th>ML Score</th><th>Amount</th>{!compact&&<th>Hard negative</th>}</tr></thead><tbody>{records.map(e=><tr key={e.evidence_id}><td className="mono">{fmtDate(e.timestamp)}</td><td>{e.attack_family}</td><td>{e.step??'—'}</td><td><Badge tone={e.sandbox_decision}>{e.sandbox_decision}</Badge></td><td>{e.evasion_outcome}</td><td className="mono">{fmtNum(e.ml_score)}</td><td className="mono">{fmtMoney(e.amount)}</td>{!compact&&<td>{e.is_hard_negative?'YES':'—'}</td>}</tr>)}</tbody></table>{!records.length&&<Empty>No evidence records yet</Empty>}</div>}
export function RunSelector({runs,value,onChange}:{runs:LoopRun[];value:string;onChange:(v:string)=>void}){return <label className="selector">Run <select value={value} onChange={e=>onChange(e.target.value)}>{runs.map(r=><option value={r.id} key={r.id}>{fmtId(r.id)} · {r.status} · {fmtDate(r.started_at)}</option>)}</select></label>}
