#!/usr/bin/env python3
"""
Generate the non-payment control-surface rules and merge them into rules.json.

These rules are what give each KB family its own verdict. The sandbox has one
handler per surface; the *control identity* of an attack comes from here plus the
family's `targeted_control_ids`. Each rule below names a specific CTL id drawn
from the families that surface serves, so a prompt-injection attempt trips
CTL-0236/0237 while a memory-poisoning attempt trips CTL-0240 — through the same
handler.

Merge is idempotent: every rule here has a `RUL-SURF-` prefix, and existing
`RUL-SURF-` rules are replaced rather than duplicated. Payment rules generated by
generate_kb_rules.py are left untouched.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "data" / "knowledge" / "canonical"

PREFIX = "RUL-SURF-"


def _rule(
    rule_id: str,
    name: str,
    engine: str,
    registry: str,
    conditions: List[Dict[str, Any]],
    risk_param: str,
    trigger: str,
    control_id: str,
    expected: List[str],
    *,
    logic: str = "all",
    signal_ids: List[str] | None = None,
    risk_default: float = 0.25,
    risk_cap: float = 0.85,
) -> Dict[str, Any]:
    return {
        "rule_id": f"{PREFIX}{rule_id}",
        "name": name,
        "rule_type": "surface",
        "engines": [engine],
        "signal_ids": signal_ids or [],
        "logic": logic,
        "conditions": conditions,
        "risk_contribution": {
            "param": risk_param,
            "registry": registry,
            "default": risk_default,
        },
        "trigger": trigger,
        "control_id": control_id,
        "expected_control_ids": expected,
        "risk_cap": risk_cap,
        "enabled": True,
        "origin": "surface_control_mapped",
    }


def _gt(field: str, param: str, registry: str, default: float) -> Dict[str, Any]:
    return {"field": field, "op": ">=", "param": param, "registry": registry, "default": default}


def _lt(field: str, param: str, registry: str, default: float) -> Dict[str, Any]:
    return {"field": field, "op": "<", "param": param, "registry": registry, "default": default}


def _flag(field: str) -> Dict[str, Any]:
    return {"field": field, "op": "truthy"}


def build_surface_rules() -> List[Dict[str, Any]]:
    rules: List[Dict[str, Any]] = []
    A, S, K, C, D, N = "agent", "auth_se", "kyc_genai", "consent", "session_integrity", "network"

    # ------------------------------------------------------------------ agent
    # AG-001 CTL-0236/0237 | AG-002 CTL-0238/0239 | AG-003 CTL-0240
    # AG-004 CTL-0241 | AG-005 CTL-0242 | GP-004 CTL-0155/0287/0288/0289
    rules += [
        _rule("AGENT-INJECTION", "Agent instruction injection", A, A,
              [_gt("prompt_injection_risk", "injection_risk_threshold", A, 0.60)],
              "injection_risk", "agent_prompt_injection", "CTL-0236",
              ["CTL-0236", "CTL-0237"], risk_default=0.30),
        _rule("AGENT-HIDDEN-INSTRUCTION", "Hidden instruction density", A, A,
              [_gt("hidden_instruction_density", "injection_risk_threshold", A, 0.60)],
              "injection_risk", "agent_hidden_instructions", "CTL-0236",
              ["CTL-0236"], risk_default=0.30),
        _rule("AGENT-GOAL-DIVERGENCE", "Agent goal divergence from user intent", A, A,
              [_gt("goal_hacking_score", "goal_divergence_threshold", A, 0.60)],
              "goal_divergence_risk", "agent_goal_divergence", "CTL-0237",
              ["CTL-0236", "CTL-0237"], risk_default=0.25),
        _rule("AGENT-IMPERSONATION", "Unverified agent identity", A, A,
              [_flag("agent_unverified_identity")],
              "impersonation_risk", "agent_unverified_identity", "CTL-0238",
              ["CTL-0238", "CTL-0239"], risk_default=0.24),
        _rule("AGENT-COUNTERPARTY", "Unverified counterparty agent", A, A,
              [_flag("agent_counterparty_unverified")],
              "impersonation_risk", "agent_counterparty_unverified", "CTL-0239",
              ["CTL-0238", "CTL-0239"], risk_default=0.24),
        _rule("AGENT-MEMORY-POISON", "Agent memory / context poisoning", A, A,
              [_gt("memory_poisoning_score", "memory_poisoning_threshold", A, 0.55)],
              "memory_poisoning_risk", "agent_memory_poisoning", "CTL-0240",
              ["CTL-0240"], risk_default=0.28),
        _rule("AGENT-MEMORY-INTEGRITY", "Agent memory integrity degraded", A, A,
              [_lt("memory_integrity", "memory_integrity_floor", A, 0.60)],
              "memory_poisoning_risk", "agent_memory_integrity_degraded", "CTL-0240",
              ["CTL-0240"], risk_default=0.28),
        _rule("AGENT-A2A", "Unauthenticated agent-to-agent channel", A, A,
              [_flag("agent_a2a_channel_unauthenticated")],
              "a2a_risk", "agent_a2a_channel_unauthenticated", "CTL-0241",
              ["CTL-0241"], risk_default=0.22),
        _rule("AGENT-TOOL-ABUSE", "Unauthorized agent tool call", A, A,
              [_gt("agentic_tool_abuse_score", "tool_abuse_threshold", A, 0.60)],
              "tool_scope_risk", "agent_unauthorized_tool_call", "CTL-0239",
              ["CTL-0239"], risk_default=0.26),
        _rule("AGENT-TOOL-SCOPE", "Agent tool scope violation", A, A,
              [_flag("agent_tool_scope_violation")],
              "tool_scope_risk", "agent_tool_scope_violation", "CTL-0289",
              ["CTL-0289"], risk_default=0.26),
        _rule("AGENT-ADAPTIVE", "Autonomous adaptive evasion by agent", A, A,
              [_gt("adaptive_evasion_score", "goal_divergence_threshold", A, 0.60)],
              "goal_divergence_risk", "agent_adaptive_evasion", "CTL-0242",
              ["CTL-0242"], risk_default=0.25),
        _rule("AGENT-MANDATE", "Agent mandate spend limit exceeded", A, A,
              [_flag("agent_mandate_limit_exceeded")],
              "protocol_abuse_risk", "agent_mandate_limit_exceeded", "CTL-0288",
              ["CTL-0155", "CTL-0287", "CTL-0288"], risk_default=0.24),
        _rule("AGENT-PROTOCOL-API", "Agentic payment protocol manipulation", A, A,
              [_gt("api_manipulation_score", "tool_abuse_threshold", A, 0.60)],
              "protocol_abuse_risk", "agent_protocol_manipulation", "CTL-0287",
              ["CTL-0155", "CTL-0287"], risk_default=0.24),
    ]

    # ---------------------------------------------------------------- auth_se
    # AUTH-001 CTL-0244..0247 | AUTH-002 CTL-0248..0250
    # AUTH-003 CTL-0091/0103/0251..0255
    rules += [
        _rule("SE-PHISHING", "Phishing content detected", S, S,
              [_gt("phishing_content_risk", "phishing_content_threshold", S, 0.60)],
              "phishing_content_risk_contribution", "se_phishing_content", "CTL-0244",
              ["CTL-0244", "CTL-0245"], risk_default=0.28),
        _rule("SE-BEC", "Business email compromise content", S, S,
              [_gt("bec_content_risk", "phishing_content_threshold", S, 0.60)],
              "phishing_content_risk_contribution", "se_bec_content", "CTL-0245",
              ["CTL-0245"], risk_default=0.28),
        _rule("SE-CHANNEL-SPOOF", "Spoofed contact channel", S, S,
              [_flag("se_channel_spoofed")],
              "channel_spoof_risk_contribution", "se_channel_spoofed", "CTL-0246",
              ["CTL-0246"], risk_default=0.24),
        _rule("SE-REPEAT-ATTEMPTS", "Repeated authentication attempts in 24h", S, S,
              [_gt("prior_attempts_24h", "max_auth_attempts_24h", S, 3)],
              "repeat_attempt_risk", "se_repeated_auth_attempts", "CTL-0247",
              ["CTL-0247"], risk_default=0.20),
        _rule("SE-VOICE-CLONE", "Synthetic / cloned voice on call", S, S,
              [_gt("voice_cloning_score", "voice_clone_threshold", S, 0.55)],
              "voice_clone_risk", "se_synthetic_voice", "CTL-0248",
              ["CTL-0248", "CTL-0249", "CTL-0250"], risk_default=0.30),
        _rule("SE-OTP-DISCLOSURE", "OTP disclosed to third party", S, S,
              [_flag("otp_disclosed")],
              "otp_disclosure_risk", "se_otp_disclosed", "CTL-0249",
              ["CTL-0248", "CTL-0249", "CTL-0250"], risk_default=0.35),
        _rule("SE-SOCIAL-PRESSURE", "Social pressure exceeds victim resistance", S, S,
              [_gt("social_pressure", "social_pressure_threshold", S, 0.60)],
              "otp_disclosure_risk", "se_social_pressure_high", "CTL-0250",
              ["CTL-0250"], risk_default=0.35),
        _rule("SE-RECOVERY-FRAUD", "Authentication recovery fraud indicators", S, S,
              [_flag("se_recovery_fraud_indicators")],
              "recovery_fraud_risk_contribution", "se_recovery_fraud", "CTL-0251",
              ["CTL-0091", "CTL-0103", "CTL-0251", "CTL-0252"], risk_default=0.28),
        _rule("SE-RECOVERY-FLOW", "Recovery flow invoked under pressure", S, S,
              [_flag("se_recovery_flow_invoked"), _gt("social_pressure", "social_pressure_threshold", S, 0.60)],
              "recovery_fraud_risk_contribution", "se_recovery_under_pressure", "CTL-0253",
              ["CTL-0253", "CTL-0254", "CTL-0255"], risk_default=0.28),
    ]

    # -------------------------------------------------------------------- kyc
    # SEP-001 CTL-0304..0307 | ATO-001 CTL-0252/0308/0309
    # ATO-002 CTL-0103/0336..0338
    rules += [
        _rule("KYC-DEEPFAKE", "Deepfake biometric at identity check", K, K,
              [_gt("deepfake_identity_score", "deepfake_threshold", K, 0.60)],
              "deepfake_risk", "kyc_deepfake_biometric", "CTL-0305",
              ["CTL-0304", "CTL-0305", "CTL-0306"], risk_default=0.35),
        _rule("KYC-BIOMETRIC-SPOOF", "Biometric spoofing indicators", K, K,
              [_gt("biometric_spoof_risk", "deepfake_threshold", K, 0.60)],
              "deepfake_risk", "kyc_biometric_spoof", "CTL-0306",
              ["CTL-0305", "CTL-0306"], risk_default=0.35),
        _rule("KYC-LIVENESS", "Liveness bypass attempt", K, K,
              [_gt("liveness_bypass_score", "liveness_bypass_threshold", K, 0.55)],
              "liveness_bypass_risk", "kyc_liveness_bypass", "CTL-0307",
              ["CTL-0307"], risk_default=0.32),
        _rule("KYC-DOC-FORGERY", "Forged identity document", K, K,
              [_gt("document_forgery_score", "document_forgery_threshold", K, 0.60)],
              "document_forgery_risk", "kyc_document_forgery", "CTL-0308",
              ["CTL-0308", "CTL-0309"], risk_default=0.32),
        _rule("KYC-DOC-TEMPLATE", "Document template reuse across submissions", K, K,
              [_flag("kyc_document_template_reuse")],
              "document_forgery_risk", "kyc_document_template_reuse", "CTL-0309",
              ["CTL-0309"], risk_default=0.32),
        _rule("KYC-RECOVERY-EVIDENCE", "Identity evidence submitted in recovery flow", K, K,
              [_flag("kyc_recovery_evidence_submitted")],
              "resubmission_risk", "kyc_recovery_evidence", "CTL-0252",
              ["CTL-0252", "CTL-0308"], risk_default=0.20),
        _rule("KYC-SYNTHETIC-IDENTITY", "Synthetic identity onboarding", K, K,
              [_gt("synthetic_identity_score", "synthetic_identity_threshold", K, 0.55)],
              "synthetic_identity_risk_contribution", "kyc_synthetic_identity", "CTL-0336",
              ["CTL-0103", "CTL-0336", "CTL-0337"], risk_default=0.28),
        _rule("KYC-CONSISTENCY", "Identity inconsistent across evidence", K, K,
              [_lt("identity_consistency_score", "identity_consistency_floor", K, 0.60)],
              "synthetic_identity_risk_contribution", "kyc_identity_inconsistent", "CTL-0338",
              ["CTL-0338"], risk_default=0.28),
        _rule("KYC-RESUBMISSION", "Repeated rejected identity submissions", K, K,
              [_gt("prior_rejected_submissions", "max_rejected_submissions", K, 2)],
              "resubmission_risk", "kyc_repeated_rejections", "CTL-0304",
              ["CTL-0304"], risk_default=0.20),
    ]

    # ----------------------------------------------------------- open_banking
    # OB-001 CTL-0213..0216 | OB-002 CTL-0217..0220
    rules += [
        _rule("OB-SCOPE-BREADTH", "Consent scope too broad", C, C,
              [_gt("consent_scope_breadth", "scope_breadth_threshold", C, 0.50)],
              "excessive_scope_risk", "ob_excessive_consent_scope", "CTL-0213",
              ["CTL-0213", "CTL-0214"], risk_default=0.28),
        _rule("OB-SENSITIVE-SCOPE", "Sensitive consent scope requested", C, C,
              [_flag("ob_sensitive_scope_requested")],
              "sensitive_scope_risk", "ob_sensitive_scope", "CTL-0214",
              ["CTL-0214"], risk_default=0.30),
        _rule("OB-SCOPE-CREEP", "Consent scope escalated after grant", C, C,
              [_flag("scope_escalation")],
              "scope_creep_risk", "ob_consent_scope_creep", "CTL-0215",
              ["CTL-0215"], risk_default=0.32),
        _rule("OB-TOKEN-REPLAY", "Consent token replay", C, C,
              [_flag("token_replay")],
              "token_replay_risk", "ob_consent_token_replay", "CTL-0216",
              ["CTL-0216"], risk_default=0.35),
        _rule("OB-DECEPTIVE-CONSENT", "Deceptive consent presentation", C, C,
              [_flag("ob_deceptive_consent_presentation")],
              "excessive_scope_risk", "ob_deceptive_consent", "CTL-0213",
              ["CTL-0213"], risk_default=0.28),
        _rule("OB-UNLICENSED-TPP", "Unlicensed third-party provider", C, C,
              [_flag("ob_unlicensed_tpp")],
              "unlicensed_tpp_risk", "ob_unlicensed_tpp", "CTL-0217",
              ["CTL-0217", "CTL-0218"], risk_default=0.34),
        _rule("OB-NEW-TPP", "Newly registered third-party provider", C, C,
              [_flag("ob_newly_registered_tpp")],
              "new_tpp_risk", "ob_newly_registered_tpp", "CTL-0218",
              ["CTL-0218"], risk_default=0.22),
        _rule("OB-SYNTHETIC-APP", "Synthetic TPP application content", C, C,
              [_flag("ob_synthetic_tpp_application")],
              "unlicensed_tpp_risk", "ob_synthetic_tpp_application", "CTL-0219",
              ["CTL-0219", "CTL-0220"], risk_default=0.34),
        _rule("OB-USAGE-ANOMALY", "Consent usage volume anomaly", C, C,
              [_flag("ob_consent_usage_anomaly")],
              "token_replay_risk", "ob_consent_usage_anomaly", "CTL-0220",
              ["CTL-0220"], risk_default=0.35),
    ]

    # ----------------------------------------------------------------- device
    # RAT-001 CTL-0139/0279..0281 | BOT-001 CTL-0013/0137/0139/0282 | BBE-001 CTL-0283
    rules += [
        _rule("DEV-REMOTE-ACCESS", "Remote access / RAT active in session", D, D,
              [_flag("dev_remote_access_detected")],
              "remote_access_risk", "dev_remote_access", "CTL-0279",
              ["CTL-0139", "CTL-0279", "CTL-0280", "CTL-0281"], risk_default=0.38),
        _rule("DEV-ACCESSIBILITY", "Accessibility service abuse", D, D,
              [_flag("dev_accessibility_abuse")],
              "remote_access_risk", "dev_accessibility_abuse", "CTL-0280",
              ["CTL-0280"], risk_default=0.38),
        _rule("DEV-OVERLAY", "Screen overlay detected", D, D,
              [_flag("dev_screen_overlay_detected")],
              "remote_access_risk", "dev_screen_overlay", "CTL-0281",
              ["CTL-0281"], risk_default=0.38),
        _rule("DEV-MACHINE-SPEED", "Machine-speed interaction timing", D, D,
              [_flag("dev_machine_speed_interaction")],
              "automation_risk", "dev_machine_speed_interaction", "CTL-0282",
              ["CTL-0013", "CTL-0137", "CTL-0282"], risk_default=0.28),
        _rule("DEV-AUTOMATION", "Automation indicators in session", D, D,
              [_flag("dev_automation_indicators")],
              "automation_risk", "dev_automation_indicators", "CTL-0137",
              ["CTL-0137"], risk_default=0.28),
        _rule("DEV-BEHAVIOURAL-VARIANCE", "Behavioural variance below human floor", D, D,
              [_flag("dev_behavioural_variance_too_low")],
              "behavioural_synthesis_risk", "dev_behavioural_variance_low", "CTL-0283",
              ["CTL-0283"], risk_default=0.30),
        _rule("DEV-SYNTHETIC-BIOMETRIC", "Synthetic behavioural telemetry", D, D,
              [_flag("dev_synthetic_biometric_telemetry")],
              "behavioural_synthesis_risk", "dev_synthetic_biometrics", "CTL-0283",
              ["CTL-0283"], risk_default=0.30),
        _rule("DEV-UNKNOWN-DEVICE", "Session from unknown device", D, D,
              [_flag("dev_unknown_device")],
              "unknown_device_session_risk", "dev_unknown_device_session", "CTL-0139",
              ["CTL-0139"], risk_default=0.24),
        _rule("DEV-SESSION-CHURN", "Excessive sessions in 1h", D, D,
              [_gt("recent_sessions_1h", "max_sessions_1h", D, 5)],
              "session_churn_risk", "dev_session_churn", "CTL-0013",
              ["CTL-0013"], risk_default=0.20),
    ]

    # ---------------------------------------------------------------- network
    # N-002 CTL-0096/0310/0315..0318 | N-003 CTL-0319..0324
    # AML-005 CTL-0035/0036/0041/0046/0047
    rules += [
        _rule("NET-RING-STRUCTURE", "Coordinated account cluster", N, N,
              [_gt("ring_size", "ring_size_threshold", N, 3)],
              "ring_structure_risk", "net_coordinated_cluster", "CTL-0315",
              ["CTL-0310", "CTL-0315", "CTL-0316"], risk_default=0.30),
        _rule("NET-LARGE-RING", "Large fraud ring structure", N, N,
              [_gt("ring_size", "large_ring_threshold", N, 8)],
              "ring_structure_risk", "net_large_ring", "CTL-0316",
              ["CTL-0316"], risk_default=0.30),
        _rule("NET-BENEFICIARY-FANIN", "Shared beneficiary fan-in across payers", N, N,
              [_gt("beneficiary_distinct_payer_count", "shared_beneficiary_payers_threshold", N, 3)],
              "shared_beneficiary_risk_contribution", "net_shared_beneficiary_fan_in", "CTL-0310",
              ["CTL-0310"], risk_default=0.32),
        _rule("NET-SHARED-DEVICE", "Device shared across accounts", N, N,
              [_flag("net_shared_device_across_accounts")],
              "shared_device_risk", "net_shared_device", "CTL-0096",
              ["CTL-0096"], risk_default=0.28),
        _rule("NET-AI-COORDINATION", "AI-coordinated ring activity", N, N,
              [_gt("fraud_ring_coordination_score", "coordination_score_threshold", N, 0.60)],
              "coordination_risk", "net_ai_ring_coordination", "CTL-0317",
              ["CTL-0317", "CTL-0318"], risk_default=0.30),
        _rule("NET-MULE-RECRUITMENT", "Mule recruitment activity", N, N,
              [_flag("net_mule_recruitment_activity")],
              "coordination_risk", "net_mule_recruitment", "CTL-0318",
              ["CTL-0318"], risk_default=0.30),
        _rule("NET-MULTI-STAGE", "Multi-stage campaign coordination", N, N,
              [_gt("multi_stage_coordination_score", "coordination_score_threshold", N, 0.60)],
              "coordination_risk", "net_multi_stage_coordination", "CTL-0319",
              ["CTL-0319", "CTL-0320", "CTL-0321"], risk_default=0.30),
        _rule("NET-AML-MANIPULATION", "AML review process manipulation", N, N,
              [_flag("net_aml_process_manipulation")],
              "aml_process_manipulation_risk", "net_aml_process_manipulation", "CTL-0035",
              ["CTL-0035", "CTL-0036", "CTL-0041"], risk_default=0.34),
        _rule("NET-LABEL-FLIPPING", "Label flipping / model poisoning attempt", N, N,
              [_flag("net_label_flipping_attempt")],
              "aml_process_manipulation_risk", "net_label_flipping", "CTL-0320",
              ["CTL-0046", "CTL-0047", "CTL-0320"], risk_default=0.34),
    ]

    # ---------------------------------------------------- cross-surface payment
    # These fire on the PAYMENT surface, driven by state left behind by an earlier
    # attack on another surface. Without them a payment is scored as if nothing
    # happened before it, and a composite campaign gains nothing from its upstream
    # steps — which is exactly the gap composite attacks exploit in production.
    P = "payment_initiation"
    rules += [
        _rule("XS-SESSION-COMPROMISED", "Payment from a compromised session", "risk", P,
              [_flag("session_compromised")],
              "amount_tier1_risk", "xs_session_compromised", "CTL-0279",
              ["CTL-0139", "CTL-0279"], risk_default=0.34),
        _rule("XS-SESSION-AUTOMATED", "Payment from an automated session", "risk", P,
              [_flag("session_automated")],
              "amount_tier1_risk", "xs_session_automated", "CTL-0282",
              ["CTL-0137", "CTL-0282"], risk_default=0.26),
        _rule("XS-OTP-DISCLOSED", "Payment after recent OTP disclosure", "risk", P,
              [_flag("otp_disclosed_recently")],
              "amount_tier1_risk", "xs_otp_disclosed_recently", "CTL-0249",
              ["CTL-0249", "CTL-0250"], risk_default=0.34),
        _rule("XS-VICTIM-COERCED", "Payment after recent coercion", "risk", P,
              [_flag("victim_coerced_recently")],
              "amount_tier1_risk", "xs_victim_coerced_recently", "CTL-0250",
              ["CTL-0250"], risk_default=0.30),
        _rule("XS-AGENT-INTEGRITY", "Payment under degraded agent integrity", "risk", P,
              [{"field": "agent_memory_integrity", "op": "exists"},
               _lt("agent_memory_integrity", "memory_integrity_floor", "agent", 0.60)],
              "amount_tier1_risk", "xs_agent_memory_degraded", "CTL-0240",
              ["CTL-0240"], risk_default=0.32),
        _rule("XS-AGENT-FIDELITY", "Payment under broken agent instruction fidelity", "risk", P,
              [{"field": "agent_instruction_fidelity", "op": "exists"},
               _lt("agent_instruction_fidelity", "memory_integrity_floor", "agent", 0.60)],
              "amount_tier1_risk", "xs_agent_fidelity_broken", "CTL-0236",
              ["CTL-0236", "CTL-0237"], risk_default=0.32),
        _rule("XS-CONSENT-PAYMENT-SCOPE", "Payment under a third-party consent scope", "risk", P,
              [_flag("consent_payment_scope_active")],
              "amount_tier1_risk", "xs_consent_payment_scope", "CTL-0215",
              ["CTL-0213", "CTL-0215"], risk_default=0.28),
        _rule("XS-CONSENT-ESCALATED", "Payment under an escalated consent", "risk", P,
              [_gt("consent_scope_escalations", "typical_scope_count", "consent", 1)],
              "amount_tier1_risk", "xs_consent_escalated", "CTL-0215",
              ["CTL-0215"], risk_default=0.28),
        _rule("XS-IDENTITY-FRESH-UPGRADE", "Payment right after an identity upgrade", "risk", P,
              [_flag("identity_recently_upgraded"),
               _lt("account_age_days", "young_account_days", "identity_kyc", 30)],
              "amount_tier1_risk", "xs_identity_fresh_upgrade", "CTL-0336",
              ["CTL-0336", "CTL-0337"], risk_default=0.30),
        _rule("XS-MULTI-SURFACE", "Payment after attacks on multiple surfaces", "risk", P,
              [_gt("compromised_surface_count", "structuring_count_threshold", "aml_compliance", 2)],
              "amount_tier1_risk", "xs_multi_surface_campaign", "CTL-0321",
              ["CTL-0319", "CTL-0321"], risk_default=0.34),
    ]

    return rules


def merge_into_rules_json(surface_rules: List[Dict[str, Any]]) -> Dict[str, Any]:
    path = BASE / "defense" / "rules.json"
    payload = json.loads(path.read_text(encoding="utf-8")) if path.exists() else {"rules": []}
    existing = [r for r in payload.get("rules", []) if not str(r.get("rule_id", "")).startswith(PREFIX)]
    rules = existing + surface_rules

    payload["rules"] = rules
    payload["built_at"] = datetime.now(timezone.utc).isoformat()
    payload["counts"] = {
        "total": len(rules),
        "threshold": sum(1 for r in rules if r.get("rule_type") == "threshold"),
        "composite": sum(1 for r in rules if r.get("rule_type") == "composite"),
        "signal": sum(1 for r in rules if r.get("rule_type") == "signal"),
        "surface": sum(1 for r in rules if r.get("rule_type") == "surface"),
    }
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return payload


def main() -> None:
    surface_rules = build_surface_rules()
    payload = merge_into_rules_json(surface_rules)
    by_engine: Dict[str, int] = {}
    controls: set = set()
    for rule in surface_rules:
        for engine in rule["engines"]:
            by_engine[engine] = by_engine.get(engine, 0) + 1
        controls.add(rule["control_id"])
    print(f"surface rules: {len(surface_rules)} across {len(by_engine)} engines")
    for engine, count in sorted(by_engine.items()):
        print(f"  {engine:18s} {count} rules")
    print(f"distinct CTL ids targeted: {len(controls)}")
    print(f"rules.json total: {payload['counts']}")


if __name__ == "__main__":
    main()
